
import java.awt.Color;









/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anonymous
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        jLabelcr.setText("<html><center>Customer <br> Records</center></html>");
        jLabelvs.setText("<html><center>View <br> Stock</center></html>");
        jLabelus.setText("<html><center>Update <br> Stock</center></html>");
        jLabelvsd.setText("<html><center>View <br> Staff Data</center></html>");
        jLabelpo.setText("<html><center>Place <br> Order</center></html>");
        jLabelusd.setText("<html><center>Update <br> Staff Data</center></html>");
        jLabelastk.setText("<html><center>Add <br> Stock</center></html>");
        jLabelas.setText("<html><center>Add <br> Staff</center></html>");
        jLabelmc.setText("<html><center>Mix <br> Colour</center></html>");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelcr = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelmc = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabelus = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabelvsd = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabelpo = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabelusd = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabelvs = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabelas = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabelastk = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("LG Paints.");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 204));

        jLabelcr.setBackground(new java.awt.Color(255, 255, 255));
        jLabelcr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelcr.setForeground(new java.awt.Color(255, 255, 255));
        jLabelcr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelcr.setText("C.R.");
        jLabelcr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelcr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelcrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelcrMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelcrMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelcr, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelcr, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 204));

        jLabelmc.setBackground(new java.awt.Color(255, 255, 255));
        jLabelmc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelmc.setForeground(new java.awt.Color(255, 255, 255));
        jLabelmc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelmc.setText("M.C.");
        jLabelmc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelmc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelmcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelmcMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelmcMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelmc, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelmc, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(0, 102, 204));

        jLabelus.setBackground(new java.awt.Color(255, 255, 255));
        jLabelus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelus.setForeground(new java.awt.Color(255, 255, 255));
        jLabelus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelus.setText("U.S.");
        jLabelus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelusMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelusMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelus, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelus, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(0, 102, 204));

        jLabelvsd.setBackground(new java.awt.Color(255, 255, 255));
        jLabelvsd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelvsd.setForeground(new java.awt.Color(255, 255, 255));
        jLabelvsd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelvsd.setText("V.S.D.");
        jLabelvsd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelvsd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelvsdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelvsdMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelvsdMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelvsd, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelvsd, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(0, 102, 204));

        jLabelpo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelpo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelpo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelpo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelpo.setText("P.O.");
        jLabelpo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelpo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelpoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelpoMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelpoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelpo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelpo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(0, 102, 204));

        jLabelusd.setBackground(new java.awt.Color(255, 255, 255));
        jLabelusd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelusd.setForeground(new java.awt.Color(255, 255, 255));
        jLabelusd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelusd.setText("U.S.D.");
        jLabelusd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelusd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelusdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelusdMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelusdMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelusd, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelusd, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(0, 102, 204));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Logout");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel9MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(23, 23, 23))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(0, 102, 204));

        jLabelvs.setBackground(new java.awt.Color(255, 255, 255));
        jLabelvs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelvs.setForeground(new java.awt.Color(255, 255, 255));
        jLabelvs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelvs.setText("V.S.");
        jLabelvs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelvs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelvsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelvsMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelvsMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelvs, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelvs, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(0, 102, 204));

        jLabelas.setBackground(new java.awt.Color(255, 255, 255));
        jLabelas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelas.setText("A.S.");
        jLabelas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelasMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelasMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelas, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelas, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel12.setBackground(new java.awt.Color(0, 102, 204));

        jLabelastk.setBackground(new java.awt.Color(255, 255, 255));
        jLabelastk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelastk.setForeground(new java.awt.Color(255, 255, 255));
        jLabelastk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelastk.setText("A.Stk");
        jLabelastk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelastk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelastkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelastkMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelastkMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelastk, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelastk, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 92, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseReleased

    private void jLabelmcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelmcMouseEntered
        // TODO add your handling code here:
        jLabelmc.setForeground(new Color(153, 255, 255));
    }//GEN-LAST:event_jLabelmcMouseEntered

    private void jLabelusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelusMouseEntered
        // TODO add your handling code here:
        jLabelus.setForeground(new Color(153, 255, 255));
    }//GEN-LAST:event_jLabelusMouseEntered

    private void jLabelvsdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelvsdMouseEntered
        // TODO add your handling code here:
        jLabelvsd.setForeground(new Color(153, 255, 255));
    }//GEN-LAST:event_jLabelvsdMouseEntered

    private void jLabelpoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelpoMouseEntered
        // TODO add your handling code here:
        jLabelpo.setForeground(new Color(153, 255, 255));
    }//GEN-LAST:event_jLabelpoMouseEntered

    private void jLabelusdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelusdMouseEntered
        // TODO add your handling code here:
        jLabelusd.setForeground(new Color(153, 255, 255));
    }//GEN-LAST:event_jLabelusdMouseEntered

    private void jLabelmcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelmcMouseExited
        // TODO add your handling code here:
        jLabelmc.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jLabelmcMouseExited

    private void jLabelusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelusMouseExited
        // TODO add your handling code here:
        jLabelus.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jLabelusMouseExited

    private void jLabelvsdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelvsdMouseExited
        // TODO add your handling code here:
        jLabelvsd.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jLabelvsdMouseExited

    private void jLabelpoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelpoMouseExited
        // TODO add your handling code here:
        jLabelpo.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jLabelpoMouseExited

    private void jLabelusdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelusdMouseExited
        // TODO add your handling code here:
        jLabelusd.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jLabelusdMouseExited

    private void jLabel9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseReleased
        // TODO add your handling code here:
        login loginnew=new login();
        loginnew.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseReleased

    private void jLabelcrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcrMouseExited
        // TODO add your handling code here:
        jLabelcr.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jLabelcrMouseExited

    private void jLabelcrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcrMouseEntered
        // TODO add your handling code here:
        jLabelcr.setForeground(new Color(153, 255, 255));
    }//GEN-LAST:event_jLabelcrMouseEntered

    private void jLabelcrMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcrMouseReleased
        // TODO add your handling code here:
        mainframe mainframenew=new mainframe();
        mainframenew.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelcrMouseReleased

    private void jLabelmcMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelmcMouseReleased
        // TODO add your handling code here:
        mainframe9 mainframenew=new mainframe9();
        mainframenew.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelmcMouseReleased

    private void jLabelusMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelusMouseReleased
        // TODO add your handling code here:
        mainframe4 mainframenew=new mainframe4();
        mainframenew.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelusMouseReleased

    private void jLabelvsdMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelvsdMouseReleased
        // TODO add your handling code here:
        mainframe5 mainframenew=new mainframe5();
        mainframenew.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelvsdMouseReleased

    private void jLabelpoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelpoMouseReleased
        // TODO add your handling code here:
        mainframe8 mainframenew=new mainframe8();
        mainframenew.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelpoMouseReleased

    private void jLabelusdMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelusdMouseReleased
        // TODO add your handling code here:
        mainframe7 mainframenew=new mainframe7();
        mainframenew.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelusdMouseReleased

    private void jLabelvsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelvsMouseEntered
        // TODO add your handling code here:
        jLabelvs.setForeground(new Color(153, 255, 255));
    }//GEN-LAST:event_jLabelvsMouseEntered

    private void jLabelvsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelvsMouseExited
        // TODO add your handling code here:
        jLabelvs.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jLabelvsMouseExited

    private void jLabelvsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelvsMouseReleased
        // TODO add your handling code here:
        mainframe2 mainframenew=new mainframe2();
        mainframenew.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelvsMouseReleased

    private void jLabelasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelasMouseEntered
        // TODO add your handling code here:
        jLabelas.setForeground(new Color(153, 255, 255));
    }//GEN-LAST:event_jLabelasMouseEntered

    private void jLabelasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelasMouseExited
        // TODO add your handling code here:
        jLabelas.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jLabelasMouseExited

    private void jLabelasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelasMouseReleased
        // TODO add your handling code here:
        mainframe6 mainframenew=new mainframe6();
        mainframenew.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelasMouseReleased

    private void jLabelastkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelastkMouseEntered
        // TODO add your handling code here:
        jLabelastk.setForeground(new Color(153, 255, 255));
    }//GEN-LAST:event_jLabelastkMouseEntered

    private void jLabelastkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelastkMouseExited
        // TODO add your handling code here:
        jLabelastk.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jLabelastkMouseExited

    private void jLabelastkMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelastkMouseReleased
        // TODO add your handling code here:
        mainframe3 mainframenew=new mainframe3();
        mainframenew.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelastkMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelas;
    private javax.swing.JLabel jLabelastk;
    private javax.swing.JLabel jLabelcr;
    private javax.swing.JLabel jLabelmc;
    private javax.swing.JLabel jLabelpo;
    private javax.swing.JLabel jLabelus;
    private javax.swing.JLabel jLabelusd;
    private javax.swing.JLabel jLabelvs;
    private javax.swing.JLabel jLabelvsd;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
