
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anonymous
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    public signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jtf_username = new javax.swing.JTextField();
        jtf_lastname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtf_address = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtf_phoneno = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jpf_password = new javax.swing.JPasswordField();
        jtf_firstname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jrb_male = new javax.swing.JRadioButton();
        jrb_female = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Sign Up");

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setText("User name");

        jtf_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_usernameActionPerformed(evt);
            }
        });

        jtf_lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_lastnameActionPerformed(evt);
            }
        });

        jLabel7.setText("First name");

        jtf_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_addressActionPerformed(evt);
            }
        });

        jLabel13.setText("Last name");

        jtf_phoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_phonenoActionPerformed(evt);
            }
        });

        jLabel14.setText("Address");

        jLabel15.setText("Password");

        jpf_password.setEchoChar('•');
        jpf_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpf_passwordActionPerformed(evt);
            }
        });

        jtf_firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_firstnameActionPerformed(evt);
            }
        });

        jLabel3.setText("Phone number");

        jLabel16.setText("Gender");

        buttonGroup1.add(jrb_male);
        jrb_male.setText("Male");

        buttonGroup1.add(jrb_female);
        jrb_female.setText("Female");
        jrb_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_femaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_username, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_address, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_phoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrb_male)
                    .addComponent(jrb_female))
                .addGap(59, 59, 59))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_username, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_phoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jrb_male)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrb_female)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_lastname))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_address, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        jPanel3.setBackground(new java.awt.Color(250, 250, 250));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Back");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel11MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("X");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel10MouseReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("LG Paints.");

        jPanel5.setBackground(new java.awt.Color(250, 250, 250));

        jLabel6.setBackground(new java.awt.Color(0, 102, 204));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Proceed");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel6MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(33, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel10)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseReleased
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel10MouseReleased

    private void jLabel11MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseReleased
        // TODO add your handling code here:
        login loginnew=new login();
        signup signupnew=new signup();
        loginnew.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseReleased

    private void jLabel6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseReleased
        // TODO add your handling code here:
        String username=jtf_username.getText();
        String firstname=jtf_firstname.getText();
        String lastname=jtf_lastname.getText();
        String address=jtf_address.getText();
        String phoneno=jtf_phoneno.getText();
        String gender = null;
        if (jrb_male.isSelected()){gender="M";}
        if (jrb_female.isSelected()){gender="F";}
        String password=jpf_password.getText();
        
        if (username.equals("") || password.equals("") || firstname.equals("") || phoneno.length()<10)
           {JOptionPane.showMessageDialog(this, "Invalid entry.");}
        else {
              try{
        Class.forName("java.sql.DriverManager");
        Connection connect=DriverManager.getConnection("jdbc:mysql://localhost/project_data","root","");
        Statement stm=connect.createStatement();
        String command="insert into login_data values('"+username+"','"+firstname+"','"+lastname+"','"+address+"','"+phoneno+"','"+gender+"','"+password+"');";
        stm.executeUpdate(command);
        connect.close();
        stm.close();
        
        JOptionPane.showMessageDialog(this, "ID successfully created. Username="+username+".");
        
        login loginnew=new login();
        loginnew.setVisible(true);
        this.dispose();
        
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "User already exists.");
            
            
        }
        }
    }//GEN-LAST:event_jLabel6MouseReleased

    private void jrb_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_femaleActionPerformed

    private void jtf_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_usernameActionPerformed
        // TODO add your handling code here:
        String username=jtf_username.getText();
        String firstname=jtf_firstname.getText();
        String lastname=jtf_lastname.getText();
        String address=jtf_address.getText();
        String phoneno=jtf_phoneno.getText();
        String gender = null;
        if (jrb_male.isSelected()){gender="M";}
        if (jrb_female.isSelected()){gender="F";}
        String password=jpf_password.getText();
        
        if (username.equals("") || password.equals("") || firstname.equals(""))
           {JOptionPane.showMessageDialog(this, "Invalid entry.");}
        else {
              try{
        Class.forName("java.sql.DriverManager");
        Connection connect=DriverManager.getConnection("jdbc:mysql://localhost/project_data","root","");
        Statement stm=connect.createStatement();
        String command="insert into login_data values('"+username+"','"+firstname+"','"+lastname+"','"+address+"','"+phoneno+"','"+gender+"','"+password+"');";
        stm.executeUpdate(command);
        connect.close();
        stm.close();
        
        JOptionPane.showMessageDialog(this, "ID successfully created. Username="+username+".");
        
        login loginnew=new login();
        loginnew.setVisible(true);
        this.dispose();
        
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
            
            
        }
        }
    }//GEN-LAST:event_jtf_usernameActionPerformed

    private void jtf_firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_firstnameActionPerformed
        // TODO add your handling code here:
        String username=jtf_username.getText();
        String firstname=jtf_firstname.getText();
        String lastname=jtf_lastname.getText();
        String address=jtf_address.getText();
        String phoneno=jtf_phoneno.getText();
        String gender = null;
        if (jrb_male.isSelected()){gender="M";}
        if (jrb_female.isSelected()){gender="F";}
        String password=jpf_password.getText();
        
        if (username.equals("") || password.equals("") || firstname.equals(""))
           {JOptionPane.showMessageDialog(this, "Invalid entry.");}
        else {
              try{
        Class.forName("java.sql.DriverManager");
        Connection connect=DriverManager.getConnection("jdbc:mysql://localhost/project_data","root","");
        Statement stm=connect.createStatement();
        String command="insert into login_data values('"+username+"','"+firstname+"','"+lastname+"','"+address+"','"+phoneno+"','"+gender+"','"+password+"');";
        stm.executeUpdate(command);
        connect.close();
        stm.close();
        
        JOptionPane.showMessageDialog(this, "ID successfully created. Username="+username+".");
        
        login loginnew=new login();
        loginnew.setVisible(true);
        this.dispose();
        
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
            
            
        }
        }
    }//GEN-LAST:event_jtf_firstnameActionPerformed

    private void jtf_lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_lastnameActionPerformed
        // TODO add your handling code here:
        String username=jtf_username.getText();
        String firstname=jtf_firstname.getText();
        String lastname=jtf_lastname.getText();
        String address=jtf_address.getText();
        String phoneno=jtf_phoneno.getText();
        String gender = null;
        if (jrb_male.isSelected()){gender="M";}
        if (jrb_female.isSelected()){gender="F";}
        String password=jpf_password.getText();
        
        if (username.equals("") || password.equals("") || firstname.equals(""))
           {JOptionPane.showMessageDialog(this, "Invalid entry.");}
        else {
              try{
        Class.forName("java.sql.DriverManager");
        Connection connect=DriverManager.getConnection("jdbc:mysql://localhost/project_data","root","");
        Statement stm=connect.createStatement();
        String command="insert into login_data values('"+username+"','"+firstname+"','"+lastname+"','"+address+"','"+phoneno+"','"+gender+"','"+password+"');";
        stm.executeUpdate(command);
        connect.close();
        stm.close();
        
        JOptionPane.showMessageDialog(this, "ID successfully created. Username="+username+".");
        
        login loginnew=new login();
        loginnew.setVisible(true);
        this.dispose();
        
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
            
            
        }
        }
    }//GEN-LAST:event_jtf_lastnameActionPerformed

    private void jtf_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_addressActionPerformed
        // TODO add your handling code here:
        String username=jtf_username.getText();
        String firstname=jtf_firstname.getText();
        String lastname=jtf_lastname.getText();
        String address=jtf_address.getText();
        String phoneno=jtf_phoneno.getText();
        String gender = null;
        if (jrb_male.isSelected()){gender="M";}
        if (jrb_female.isSelected()){gender="F";}
        String password=jpf_password.getText();
        
        if (username.equals("") || password.equals("") || firstname.equals(""))
           {JOptionPane.showMessageDialog(this, "Invalid entry.");}
        else {
              try{
        Class.forName("java.sql.DriverManager");
        Connection connect=DriverManager.getConnection("jdbc:mysql://localhost/project_data","root","");
        Statement stm=connect.createStatement();
        String command="insert into login_data values('"+username+"','"+firstname+"','"+lastname+"','"+address+"','"+phoneno+"','"+gender+"','"+password+"');";
        stm.executeUpdate(command);
        connect.close();
        stm.close();
        
        JOptionPane.showMessageDialog(this, "ID successfully created. Username="+username+".");
        
        login loginnew=new login();
        loginnew.setVisible(true);
        this.dispose();
        
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
            
            
        }
        }
    }//GEN-LAST:event_jtf_addressActionPerformed

    private void jtf_phonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_phonenoActionPerformed
        // TODO add your handling code here:
        String username=jtf_username.getText();
        String firstname=jtf_firstname.getText();
        String lastname=jtf_lastname.getText();
        String address=jtf_address.getText();
        String phoneno=jtf_phoneno.getText();
        String gender = null;
        if (jrb_male.isSelected()){gender="M";}
        if (jrb_female.isSelected()){gender="F";}
        String password=jpf_password.getText();
        
        if (username.equals("") || password.equals("") || firstname.equals(""))
           {JOptionPane.showMessageDialog(this, "Invalid entry.");}
        else {
              try{
        Class.forName("java.sql.DriverManager");
        Connection connect=DriverManager.getConnection("jdbc:mysql://localhost/project_data","root","");
        Statement stm=connect.createStatement();
        String command="insert into login_data values('"+username+"','"+firstname+"','"+lastname+"','"+address+"','"+phoneno+"','"+gender+"','"+password+"');";
        stm.executeUpdate(command);
        connect.close();
        stm.close();
        
        JOptionPane.showMessageDialog(this, "ID successfully created. Username="+username+".");
        
        login loginnew=new login();
        loginnew.setVisible(true);
        this.dispose();
        
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
            
            
        }
        }
    }//GEN-LAST:event_jtf_phonenoActionPerformed

    private void jpf_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpf_passwordActionPerformed
        // TODO add your handling code here:
        String username=jtf_username.getText();
        String firstname=jtf_firstname.getText();
        String lastname=jtf_lastname.getText();
        String address=jtf_address.getText();
        String phoneno=jtf_phoneno.getText();
        String gender = null;
        if (jrb_male.isSelected()){gender="M";}
        if (jrb_female.isSelected()){gender="F";}
        String password=jpf_password.getText();
        
        if (username.equals("") || password.equals("") || firstname.equals(""))
           {JOptionPane.showMessageDialog(this, "Invalid entry.");}
        else {
              try{
        Class.forName("java.sql.DriverManager");
        Connection connect=DriverManager.getConnection("jdbc:mysql://localhost/project_data","root","");
        Statement stm=connect.createStatement();
        String command="insert into login_data values('"+username+"','"+firstname+"','"+lastname+"','"+address+"','"+phoneno+"','"+gender+"','"+password+"');";
        stm.executeUpdate(command);
        connect.close();
        stm.close();
        
        JOptionPane.showMessageDialog(this, "ID successfully created. Username="+username+".");
        
        login loginnew=new login();
        loginnew.setVisible(true);
        this.dispose();
        
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
            
            
        }
        }
    }//GEN-LAST:event_jpf_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField jpf_password;
    private javax.swing.JRadioButton jrb_female;
    private javax.swing.JRadioButton jrb_male;
    private javax.swing.JTextField jtf_address;
    private javax.swing.JTextField jtf_firstname;
    private javax.swing.JTextField jtf_lastname;
    private javax.swing.JTextField jtf_phoneno;
    private javax.swing.JTextField jtf_username;
    // End of variables declaration//GEN-END:variables
}
